version: "3.7"

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    volumes:
      - /var/lib/redis/data

  api:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    volumes:
      - ./backend:/app

  scrapers:
    build:
      context: ./
      dockerfile: ./docker/scrapers/Dockerfile
    volumes:
      - ./scrapers:/app
      - /etc/localtime:/etc/localtime:ro
