# Generated by Django 2.1.7 on 2019-02-17 19:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=16, max_digits=32)),
                ('type', models.CharField(max_length=64)),
                ('base_currency_code', models.CharField(max_length=3)),
                ('target_currency_code', models.CharField(max_length=3)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('date', 'target_currency_code')},
        ),
    ]
